apiVersion: v1
kind: Service
metadata:
  name: myapp-mysql
  namespace: default
spec:
  selector:
    app: segundo-pod
  type: NodePort
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  


