apiVersion: v1
kind: Service
metadata:
  name: myapp-svc2
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: segundo-pod
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306